In [78]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler

In [79]:
df = pd.read_csv("/content/lasso_regression_practice.csv")

In [80]:
df.head(2)

   area_sqft  bedrooms  bathrooms  ...  noise_feature_2  noise_feature_3  price_lakh
0       1846         3          4  ...           -1.942            0.659      151.34
1       1622         5          2  ...            1.419            0.711      123.85

[2 rows x 13 columns]

In [84]:
X = df.iloc[:,:-1]
y = df['price_lakh']

In [85]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [86]:
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [87]:
SLR = LinearRegression()
SLR.fit(X_train , y_train)
SLR_Predict = SLR.predict(X_test)
r2_score(y_test , SLR_Predict)

0.9543218109949652

In [88]:
Lasso_model = Lasso(alpha=0.01)
Lasso_model.fit(X_train_scaler , y_train)
Lasso_predict = Lasso_model.predict(X_test_scaler)
r2_score(y_test , Lasso_predict)

0.9544557230353304

## Lets Create a Own Lasso Class With GD

In [89]:
class MeraLasso:

  def __init__(self, Lr , epochs , lam):
    self.Lr = Lr
    self.epochs =epochs
    self.lam = lam

    self.m = None
    self.b = None

  def fit(self,X_train , y_train):
    self.b = 0
    self.m = np.ones(X_train.shape[1])

    for i in range(self.epochs):
      for j in range(X_train.shape[0]):

        idx = np.random.randint(0 , X_train.shape[0])

        y_hat = np.dot(X_train[idx] , self.m) + self.b

        slope_loss_b = -2 * (y_train.iloc[idx] - y_hat)
        self.b = self.b - self.Lr * slope_loss_b

        slope_loss_m = (
            -2 * np.dot((y_train.iloc[idx] - y_hat), X_train[idx])
            + 2 * self.lam * np.sign(self.m)
        )

        self.m = self.m - self.Lr * slope_loss_m

  def predict(self,X_test):
    y_pred = np.dot(X_test , self.m) + self.b
    return y_pred

In [93]:
MyLasso = MeraLasso(0.01 , 200 , 0.00001)
MyLasso.fit(X_train_scaler , y_train)
y_pred = MyLasso.predict(X_test_scaler)
r2_score(y_test , y_pred)

0.9448887143677602

In [60]:
X_train_scaler[4]

array([ 1.33789683, -1.27829255, -0.53881591,  0.02345751, -1.48670396])

In [54]:
idx = np.random.randint(0 , X_train.shape[0])

In [64]:
y_train[3]

np.float64(144.48)

In [76]:
y_pred = MyRidge.predict([ 1.57859671,  0.87462122,  0.90802651,  0.12345751,  0.32388062])

In [77]:
y_pred

np.float64(203.81550007077237)

In [75]:
df.head(2)

   area_sqft  bedrooms  bathrooms  age_years  distance_to_city_km  price_lakh
0       1360         5          5         19                  7.1      142.56
1       1794         4          3         23                  8.1      133.30